version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    container_name: app

  postgres:
    image: postgres:16
    volumes:
      - ./tmp/db:/var/lib/postgres
    environment:
      POSTGRES_DB: apteka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5432
    restart: always
    container_name: pstg


    
